set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim " vundleのインストール先
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" Directory Tree View
" usage enter :NERDTree in ex mode
Plugin 'scrooloose/nerdtree'
"Plugin 'junegunn/fzf'
"Plugin 'junegunn/fzf.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'previm/previm'


" Indent Seeing
Plugin 'nathanaelkane/vim-indent-guides'

call vundle#end()
filetype plugin indent on

" この後は、好きな設定を入れる
set number
set fenc=utf-8
set showcmd
set cursorline
set cursorcolumn
set showmatch
set ignorecase
set smartcase
set incsearch
set wrapscan
set columns=180
